const menu = [
    {
      id: 1,
      title: 'buttermilk pancakes',
      category: 'breakfast',
      price: 15.99,
      img: 'https://api.creativecommons.engineering/v1/thumbs/8ef0905e-a044-4ce3-8f18-461eac9ede17',
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
      id: 2,
      title: 'diner double',
      category: 'lunch',
      price: 13.99,
      img: 'https://live.staticflickr.com/4014/4429119391_7cc724be5e_b.jpg',
      desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
    },
    {
      id: 3,
      title: 'godzilla milkshake',
      category: 'shakes',
      price: 6.99,
      img: 'https://api.creativecommons.engineering/v1/thumbs/cde007c0-5e0a-4e10-808b-89bb6a10f25f',
      desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
    },
    {
      id: 4,
      title: 'country delight',
      category: 'breakfast',
      price: 20.99,
      img: 'https://api.creativecommons.engineering/v1/thumbs/40e10b9a-fb3b-4024-8e75-cd11779760b5',
      desc: `bulb, palo santo farm-to-table 90's raw denim slow-carb vaporware`,
    },
    {
      id: 5,
      title: 'egg attack',
      category: 'lunch',
      price: 22.99,
      img: 'https://api.creativecommons.engineering/v1/thumbs/c2dce20b-1ba0-45f7-b2e0-04d33aa546ab',
      desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
    },
    {
      id: 6,
      title: 'oreo dream',
      category: 'shakes',
      price: 18.99,
      img: 'https://api.creativecommons.engineering/v1/thumbs/8e23e6d4-1f8a-459a-b75b-d4efe4797824',
      desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
    },
    {
      id: 7,
      title: 'bacon overflow',
      category: 'breakfast',
      price: 8.99,
      img: 'https://api.creativecommons.engineering/v1/thumbs/95d46e08-fd8e-4d3b-8b66-8630ba63e666',
      desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
    },
    {
      id: 8,
      title: 'american classic',
      category: 'lunch',
      price: 12.99,
      img: 'https://api.creativecommons.engineering/v1/thumbs/70874ace-b34e-439d-bb77-7c663d460a12',
      desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
    },
    {
      id: 9,
      title: 'quarantine buddy',
      category: 'shakes',
      price: 16.99,
      img: 'https://api.creativecommons.engineering/v1/thumbs/6e33dc3c-5b9e-48aa-9278-67a36d70c7dd',
      desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    },
  ];
  export default menu;